// GENERAL
// ---------
// Set up Snowflake 

USE ROLE SYSADMIN;

-- For Better UI usage
USE WAREHOUSE COMPUTE_WH;

-- create warehouse for compute
USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE DEMO_SNOWFLAKE_FABRIC_WH
WAREHOUSE_TYPE = STANDARD
WAREHOUSE_SIZE = 'X-Small'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED=TRUE
COMMENT = 'Warehouse for Demo case for Database mirroring with Fabric';

CREATE OR REPLACE DATABASE DEMO_FABRIC_MIRROR
COMMENT = 'Database for storing data which should be mirrored to Fabric';

USE ROLE SYSADMIN;
USE DATABASE DEMO_FABRIC_MIRROR;
CREATE OR REPLACE SCHEMA DEMO_FABRIC_MIRROR.TP_CH_SF10;

-- DB roles for access to database objects
CREATE OR REPLACE DATABASE ROLE DEMO_FABRIC_MIRROR.DR_DEMO_FABRIC_MIRROR_TP_CH_SF10_MIRRORING 
COMMENT= 'Access role only for mirroring in the schema TP_CH_SF10';

GRANT USAGE ON DATABASE DEMO_FABRIC_MIRROR TO DATABASE ROLE  DEMO_FABRIC_MIRROR.DR_DEMO_FABRIC_MIRROR_TP_CH_SF10_MIRRORING;
GRANT USAGE ON SCHEMA DEMO_FABRIC_MIRROR.TP_CH_SF10 TO DATABASE ROLE  DEMO_FABRIC_MIRROR.DR_DEMO_FABRIC_MIRROR_TP_CH_SF10_MIRRORING;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_FABRIC_MIRROR.TP_CH_SF10  TO DATABASE ROLE  DEMO_FABRIC_MIRROR.DR_DEMO_FABRIC_MIRROR_TP_CH_SF10_MIRRORING;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_FABRIC_MIRROR.TP_CH_SF10 TO DATABASE ROLE  DEMO_FABRIC_MIRROR.DR_DEMO_FABRIC_MIRROR_TP_CH_SF10_MIRRORING;
GRANT CREATE STREAM ON SCHEMA DEMO_FABRIC_MIRROR.TP_CH_SF10  TO DATABASE ROLE  DEMO_FABRIC_MIRROR.DR_DEMO_FABRIC_MIRROR_TP_CH_SF10_MIRRORING;

USE ROLE SECURITYADMIN;
-- Functional roles for accessing compute
CREATE OR REPLACE ROLE FR_DEMO_SNOWFLAKE_FABRIC_WH 
COMMENT = 'FUNCTIONAL ROLE FOR ADMINISTERING WAREHOUSE DEMO_SNOWFLAKE_FABRIC_WH';

CREATE OR REPLACE ROLE FR_DEMO_SNOWFLAKE_FABRIC_WH_USAGE
COMMENT = 'FUNCTIONAL ROLE FOR USING WAREHOUSE DEMO_SNOWFLAKE_FABRIC_WH';

USE ROLE SECURITYADMIN;
GRANT ALL ON WAREHOUSE DEMO_SNOWFLAKE_FABRIC_WH TO FR_DEMO_SNOWFLAKE_FABRIC_WH;
GRANT USAGE ON WAREHOUSE DEMO_SNOWFLAKE_FABRIC_WH TO FR_DEMO_SNOWFLAKE_FABRIC_WH_USAGE;

-- create functional role for permission management
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE FR_DEMO_FABRIC_MIRRORING
COMMENT = 'Functional role to combine rights for Snowflake mirroring in Fabric Demo';

GRANT ROLE FR_DEMO_SNOWFLAKE_FABRIC_WH_USAGE TO ROLE FR_DEMO_FABRIC_MIRRORING;
GRANT DATABASE ROLE DEMO_FABRIC_MIRROR.DR_DEMO_FABRIC_MIRROR_TP_CH_SF10_MIRRORING to role FR_DEMO_FABRIC_MIRRORING;

SHOW GRANTS TO role FR_DEMO_FABRIC_MIRRORING;
SHOW GRANTS TO DATABASE role DEMO_FABRIC_MIRROR.DR_DEMO_FABRIC_MIRROR_TP_CH_SF10_MIRRORING;

-- create technical user to connect from fabric
USE ROLE SECURITYADMIN;
CREATE OR REPLACE USER DEMO_FABRIC_SNOWFLAKE
    PASSWORD = 'XXX'
    DEFAULT_ROLE = FR_DEMO_FABRIC_MIRRORING
    DEFAULT_WAREHOUSE = DEMO_SNOWFLAKE_FABRIC_WH
    MUST_CHANGE_PASSWORD = FALSE;
    
GRANT ROLE FR_DEMO_FABRIC_MIRRORING to user DEMO_FABRIC_SNOWFLAKE;

-- ===================================================================================================================================================

USE ROLE SYSADMIN;
USE DATABASE demo_fabric_mirror;
USE SCHEMA tp_ch_sf10;

CREATE OR REPLACE TABLE CUSTOMER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER;
CREATE OR REPLACE TABLE LINEITEM AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM;
CREATE OR REPLACE TABLE ORDERS AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS;

ALTER TABLE DEMO_FABRIC_MIRROR.TP_CH_SF10.CUSTOMER set CHANGE_TRACKING=TRUE;
ALTER TABLE DEMO_FABRIC_MIRROR.TP_CH_SF10.LINEITEM set CHANGE_TRACKING=TRUE;
ALTER TABLE DEMO_FABRIC_MIRROR.TP_CH_SF10.ORDERS set CHANGE_TRACKING=TRUE;


/* -- further tables for possible demonstration
create or replace table NATION as select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION;
create or replace table PART as select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART;
create or replace table PARTSUPP as select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP;
create or replace table REGION as select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION;
create or replace table SUPPLIER as select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER;

ALTER TABLE DEMO_FABRIC_MIRROR.TP_CH_SF10.NATION set CHANGE_TRACKING=TRUE;
ALTER TABLE DEMO_FABRIC_MIRROR.TP_CH_SF10.PART set CHANGE_TRACKING=TRUE;
ALTER TABLE DEMO_FABRIC_MIRROR.TP_CH_SF10.PARTSUPP set CHANGE_TRACKING=TRUE;
ALTER TABLE DEMO_FABRIC_MIRROR.TP_CH_SF10.REGION set CHANGE_TRACKING=TRUE;
ALTER TABLE DEMO_FABRIC_MIRROR.TP_CH_SF10.SUPPLIER set CHANGE_TRACKING=TRUE;

*/

-->> schema populated with data to be mirrored + permissions set so that Fabric can connect

SELECT COUNT(*) FROM CUSTOMER;
SELECT COUNT(*) FROM LINEITEM;
SELECT COUNT(*) FROM ORDERS;

INSERT INTO CUSTOMER (C_CUSTKEY,C_NAME)
VALUES ('15000001', 'DEMOINSERT');

DELETE FROM CUSTOMER
WHERE C_CUSTKEY = '15000001';

/* -- cleanup block */
DROP USER IF EXISTS DEMO_FABRIC_SNOWFLAKE;
DROP WAREHOUSE IF EXISTS DEMO_SNOWFLAKE_FABRIC_WH; 
DROP ROLE IF EXISTS FR_DEMO_FABRIC_MIRRORING;
DROP ROLE IF EXISTS FR_DEMO_SNOWFLAKE_FABRIC_WH;
DROP ROLE IF EXISTS FR_DEMO_SNOWFLAKE_FABRIC_WH_USAGE;
DROP DATABASE IF EXISTS DEMO_FABRIC_MIRROR;